automated-checks.sh
Use build_app as the file to prevent a conflict with XCode, make the PR non-interactive
=> Improve automations

automated-checks.sh
Check for image changes, spacing and re-organisation of declared variables
=> Improve the automated build script

automated-checks.sh
Fix automated build script, no local paths and fix Assets
=> Fix automations

automated-checks.sh
Fix rm of a file that may not exist, add cleaning
=> More automation improvements

Elsewhen/Elements/ResultSheet.swift, Elsewhen/Views/MykeMode.swift
(May or may not improve support for Universal Clipboard)
=> Use the newer UTType.utf8PlainText rather than deprecated kUTTypePlainText

Elsewhen.xcodeproj/project.pbxproj
=> Release 13

Elsewhen.xcodeproj/project.pbxproj, build_app
=> Release 14

Elsewhen.xcodeproj/project.pbxproj, build_app
Build please Rose! Wed 15 Sep 2021 19:44:30 BST
=> Release 15

Elsewhen.xcodeproj/project.pbxproj, build_app
Build please Rose! Wed 15 Sep 2021 21:49:38 BST
=> Release 16

Elsewhen.xcodeproj/project.pbxproj, build_app
=> Release 17

Elsewhen/Elements/DateTimeSelection.swift, Elsewhen/Elements/DateTimeZonePicker.swift, Elsewhen/Views/MykeMode.swift, MacElsewhen/Controllers/StatusBar/StatusBarPopoverController.swift
Also makes detached popover movable
=> macOS: Use popovers date selection

Elsewhen/Elements/TimeZoneChoice/TimezoneChoiceView.swift, Elsewhen/Views/MykeMode.swift
=> Fix weirdness when deleting timezones via context menu

Elsewhen/Views/Settings.swift
=> Comment out settings for App Icon release

Elsewhen.xcodeproj/project.pbxproj, Elsewhen/Elements/Buttons/EasterEggButton.swift, Elsewhen/Elements/NotRepresentativeWarning.swift, Localizable.strings
Not really for localisation but for consistency across platforms
(Moves the "NotRepresentativeWarning" and "From the Lovely Developers"
=> Move some strings into localisation file

Elsewhen.xcodeproj/project.pbxproj, Elsewhen/Views/EasterEggView.swift, MacElsewhen/Controllers/StatusBar/TimeCodesPopoverViewController.swift, MacElsewhen/Credits.rtf
- TLD credit in About box
- (Smaller) returns easter egg in popover
=> Some niceties

Elsewhen/Views/Settings.swift
This reverts commit abd880ac43d97efb6596400820b4789820cf4cfe.
=> Revert "Comment out settings for App Icon release"

Discord Helper Intents/TimeListIntentHandling.swift, Elsewhen.xcodeproj/project.pbxproj, Elsewhen/Elements/MykeMode/SelectedTimeZoneCell.swift, Elsewhen/Elements/TimeZoneChoice/TimezoneChoiceView.swift, Elsewhen/Extensions/UserDefaults.swift, Elsewhen/Helpers/DateHelpers.swift, Elsewhen/Helpers/TimeZoneFlags.swift, Elsewhen/Views/MykeMode.swift, Elsewhen/Views/Settings.swift, Elsewhen/Views/SettingsComponents/DefaultTimeFormatPicker.swift, Elsewhen/Views/SettingsComponents/SeparatorPicker.swift, Elsewhen/Views/SettingsComponents/TimeListSettings.swift, MacElsewhen/Views/PreferencesViewController.swift, MacElsewhen/Views/PreferencesViewController.xib
- Time List shows output style
- Context menu option to swap flag for clock etc
- Settings shows example output style
=> Time List display changes

Elsewhen/Elements/DateTimeZonePicker.swift, Elsewhen/ElsewhenApp.swift, Elsewhen/Views/MykeMode.swift, MacElsewhen/Views/ContentTabViewController.swift
=> Improvements to MykeMode UI on macOS

Elsewhen/Views/TimeCodeGeneratorView.swift
=> Show local time on Time Code view when a non-local time zone is selected

MacElsewhen/Controllers/StatusBar/StatusItemTabViewController.swift, MacElsewhen/Controllers/StatusBar/TimeCodesPopoverViewController.swift, MacElsewhen/Controllers/StatusBar/TimeListPopoverViewController.swift
There was a missing `EnvironmentObject`
=> Fix macos status bar dropdown
